---
- hosts: 172.31.17.207
  become: yes
  tasks:
  - name: install webserver on redhat
    yum:
      name: httpd
      state: present
    notify: restart webserver  
    when: ansible_os_family =="RedHat"


  - name: copy index.j2 into webserver
    template:
      src: index.j2
      dest: /etc/httpd.conf

    notify: restart webserver
    when: ansible_os_family =="RedHat" 

  handlers:
  - name: restart webserver
    service:
      name: httpd
      state: restarted
