---
- hosts: webservers
  become: yes
  tasks: 
  - include_tasks: ansible1.yml
  - name: install webserversate
    apt: 
      name: apache2
      state: present
  - when: ansible_os_family =="debain"
  - name: apache2 service start
    service: 
      name: apache2
      state: started
  - when: ansible_os_family =="debain"