---
- hosts: 172.31.30.60
  become: yes
  tasks:
  - name: install git
    apt:
      name: git


  - name: install tree
    apt: 
      name: tree    


  - name: install wget
    apt:
      name: wget    
    skip: yes  