---
- hosts: 172.31.30.60
  become: yes
  tasks:
  - name: install tree
    apt:
      name: tree
      state: present
    tags: 1st 
  - name: install git
    apt:
      name: git
      state: present
    tags: 2nd  
  - name: install wget
    apt:
     name: wget
     state: present
    tags: 3rd
