---
# tasks file for tomwebrole
- include_tasks: installjava.yml
- include_tasks: tomusergroup.yml
- include_tasks: download.yml
- include_tasks: extract.yml
- include_tasks: Permissions.yml
- include_tasks: tomconfig.yml
- include_tasks: tomstart.yml
- include_tasks: tomuser.yml
- include_tasks: tomrestart.yml

