---
- name: create group
  group:
    name: tomcat
    state: present

- name: create user
  user:
    name: tomcat
    comment: my tom user
    group: tomcat
    shell: bin/false
    home: /opt/tomcat